[package]
name = "voxelize"
version = "0.8.36"
description = "A fast multiplayer voxel engine."
edition = "2021"
license = "MIT"

[lib]
name = "voxelize"
path = "src/lib.rs"

[dependencies]
actix = "0.13.0"
actix-web-actors = "4.2.0"
serde = "1.0.163"
serde_json = "1.0.96"